# Generated by Django 3.2.14 on 2022-07-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agencia.marca')),
            ],
        ),
    ]
